name: DAST Scan (OWASP ZAP)

on:
  push:
    branches:
      - feature/truong

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
          echo " Waiting for Juice Shop to start..."
          sleep 40

      - name: Run OWASP ZAP baseline scan
        run: |
          mkdir zap-results
          docker run --network="host" \
            -v ${{ github.workspace }}/zap-results:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-DAST-Report
          path: zap-results/zap-report.html
