name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Juice Shop image
        run: docker pull bkimminich/juice-shop

      - name: Start Juice Shop container
        run: |
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
          echo " Waiting for Juice Shop to start..."
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo " Juice Shop is up!"
              break
            fi
            echo "Still waiting... ($i/10)"
            sleep 10
          done

      - name: Pull OWASP ZAP image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-results
          docker run --network host -v $(pwd)/zap-results:/zap/wrk ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:3000 -r zap-report.html
          ls zap-results

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-DAST-Report
          path: zap-results/zap-report.html
