name: SBOM and Image Security Scan

on:
  workflow_call: # Called by main pipeline
  workflow_dispatch: # Can be triggered manually
  push:
    branches:
      - feature/hoang_anh

jobs:
  
  sca-with-snyk:
    name: SCA Synk Scan
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      security-events: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install Dependancy
        run: npm ci --legacy-peer-deps
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          command: test
          args: --sarif-file-output=snyk.sarif
        
      - name: Upload result to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk.sarif

  owasp-dependency-check:
    name: OWASP Dependency-Check Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps

    
      - name: Run OWASP Dependency-Check Scan
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'SARIF'
        # Chúng ta biết chắc file sẽ được tạo ra trong thư mục này
          out: './reports'
          args: >
             --exclude "**/frontend/dist/**"
             --exclude "**/ftp/**"
             --exclude "**/owasp_promo.vtt"
             --exclude "**/legal.md"
    
   
      - name: Upload OWASP Dependency-Check results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
        # Chúng ta không dùng output nữa.
        # Thay vào đó, chúng ta cung cấp đường dẫn trực tiếp đến file báo cáo.
        # Đường dẫn này khớp với giá trị 'out' ở trên và tên file mặc định.
          sarif_file: './reports/dependency-check-report.sarif'
          category: owasp-dependency-check
  
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate SBOM with Syft 
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: "sbom.json" 
      - name: Upload SBOM Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom.json

  scan-sbom-grype:
    name: Scan Sbom Grype
    runs-on: ubuntu-latest
    needs: generate-sbom
    
    steps:
      - name: Download SBOM Artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-${{ github.sha }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Grype vulnerability scanner on sbom
    # Sử dụng action chính thức của Grype
        uses: anchore/scan-action@v6
        continue-on-error: true
        with:
          sbom: "sbom.json"
          output-format: table
      
