name: SBOM and Image Security Scan

on:
  workflow_call: # Called by main pipeline
  workflow_dispatch: # Can be triggered manually
  push:
    branches:
      - feature/hoang_anh

jobs:
  sast-with-sonarqube:
    name: SAST Sonarqube Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarQube to Scan vulnerabilities 
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          continue-on-erro: true

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 10
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  

  # ------ JOB 3: QUÉT VỚI OWASP DEPENDENCY-CHECK ------
  owasp-dependency-check:
    name: OWASP Dependency-Check Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      # Bước cài đặt riêng cho job này
      - name: Install Dependencies for OWASP
        run: npm ci --legacy-peer-deps

      - name: Run OWASP Dependency-Check
        id: DepCheck
        uses: dependency-check/Dependency-Check_Action@main
        # continue-on-error: true # Bật nếu bạn muốn workflow tiếp tục dù có lỗi
        with:
          project: 'juice-shop'
          scan: '.' 
          format: 'SARIF'
          # Các đối số loại trừ để tránh lỗi với các tệp "bẫy"
          scan-args: >-
            --exclude "**/frontend/dist/**"
            --exclude "**/ftp/**"
            --node-audit-analyzer-enabled false
            --retire-js-analyzer-enabled false
      
      - name: Upload OWASP results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Dùng always() vì DepCheck có thể fail nếu tìm thấy lỗi
        with:
          category: owasp-dependency-check
          sarif_file: ${{ steps.DepCheck.outputs.sarif_file }}
      
      - name: Upload OWASP Dependency-Check results
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: owasp-dependency-check
          sarif_file: ${{ steps.DepCheck.outputs.sarif_file }}

      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ${{ steps.DepCheck.outputs.html_file }}