
name: Scan OS and Kernel on EC2

on:
  push:
    branches: 
      - 'feature/hoang_anh'

env:
  IMAGE_TO_SCAN: dinhtrkien/owasp-juice-shop:latest

jobs:
  trivy-scan:
    name: Scan with Trivy on EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH to EC2 and run Trivy scan
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "--- Checking disk space before scan ---"
            df -h
            
            echo "--- Cleaning up unused Docker resources ---"
            docker system prune -af || true
            
            set -e # Dừng ngay lập tức nếu có lỗi

            echo "Scanning ${{ env.IMAGE_TO_SCAN }} with Trivy..."

            # 1. Cài đặt Trivy nếu cần
            if ! command -v trivy &> /dev/null
            then
                echo "Trivy not found. Installing now..."
                curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
            fi

            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
            sudo trivy rootfs / --scanners vuln --format table --severity HIGH,CRITICAL


  
