name: "SAST Scanning"

# Truong's workflow - Static Application Security Testing
# This workflow is called by security-enhanced.yml OR can run independently

on:
  workflow_call: # Called by main pipeline
  workflow_dispatch: # Can be triggered manually
  push:
    branches:
      - feature/truong

jobs:
  sonarqube_scan:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_55747d6019873f56928891d88c6263dce964bb5e
          SONAR_HOST_URL: http://35.172.114.185:9000
        with:
          args: >
            -Dsonar.projectKey=juice-shop
            -Dsonar.projectName=juice-shop


